language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] sudo apt-get install xorg-dev libglu1-mesa-dev

script:
  - mkdir Build && cd Build
  - cmake ..
